# causal model ------------------------------------------------------------

#' Build a simple toy-model capable of predictions under interventions, on a
#' simple dataset.
#'
#' @param data A data.frame as generated by build_data(n), with at least
#'   treatment variable A, confounder L, prognostic variable P, and outcome Y
#'
#' @returns A GLM for the outcome Y with independent variables treatment A and
#'   prognostic variable P. It has been fitted using IP weighting, conditional
#'   on confounder L.
#' @export
#'
#' @examples
#' df_dev <- build_data(1000)
#' causal_model <- build_causal_model(df_dev)
#' summary(causal_model)
#' # Compare this to the 'naive' model
#' naive_model <- glm(Y ~ A + P, family = "binomial", data = df_dev)
#' summary(naive_model)
#' # In the naive model, treatment increases the risk due to the confounding of L.
#' # This has been adjusted for appropriately in the causal model.
build_causal_model <- function(data) {
  propensity_model <- stats::glm(A ~ L, family = "binomial", data = data)
  prop_score <- stats::predict(propensity_model, type = "response")
  prob_trt <- ifelse(data$A == 1, prop_score, 1 - prop_score)
  ipw <- 1 / prob_trt

  stats::glm(Y ~ A + P, family = "binomial", data = data, weights = ipw)
}
